### ISSUE TITLE
task: add proper handling of GPT KEY as ENV

### ISSUE THREAD

**Issue by YohannParis** [mikecafarella/mitaskem#38]
### Description

Currently, the implementation of GPT_KEY in the app lacks consistency, being randomly assigned through methods like file import or request parameters. To enhance both deployment convenience and security, there is a need to refactor how access to the key is managed.

For instance, when considering the scenario of file import, the following approach could be adopted:
```python
import os
import gpt_key
# Prioritize the environment variable if present, otherwise use the imported key
GPT_KEY = os.environ.get("GPT_KEY", getattr(gpt_key, 'GPT_KEY', None))
```

**Comment by Tranway1** [comment]
fixed with the latest version

**Comment by Tranway1** [comment]
fixed with the latest version
